"use client";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";

/**
 * Renders a document's markdown as the live preview and print target. Templates
 * use GitHub-flavored markdown (tables, "- [ ]" checkboxes) plus a little inline
 * HTML, so we enable remark-gfm and rehype-raw. The `document-preview` class is
 * the print isolation target (see globals.css).
 */
export const DISCLAIMER =
  "This is a draft generated by AI. It is not legal advice and is subject to " +
  "review by a qualified attorney before use.";

export default function DocumentPreview({ markdown }: { markdown: string }) {
  return (
    <article className="document-preview rounded-lg border border-slate-200 bg-white p-8 text-sm leading-relaxed text-slate-800 shadow-sm">
      <p className="document-disclaimer" role="note">
        <strong>Draft — not legal advice.</strong> {DISCLAIMER}
      </p>
      <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw]}>
        {markdown}
      </ReactMarkdown>
    </article>
  );
}
